parameters:
    kairos.doctrine_behaviors.usageorderable.class: Kairos\DoctrineBehaviors\Model\UsageOrderable\Manager\UsageOrderableManager
    kairos.doctrine_behaviors.usageorderable_listener.class: Kairos\DoctrineBehaviors\ORM\UsageOrderable\UsageOrderableListener
    kairos.doctrine_behaviors.usageorderable.usageorderable_trait: Kairos\DoctrineBehaviors\Model\UsageOrderable\UsageOrderable
    kairos.doctrine_behaviors.usageorderable.usagetimestamp_trait: Kairos\DoctrineBehaviors\Model\UsageOrderable\UsageTimestamp

services:

    kairos.doctrine_behaviors.usageorderable:
        class:   "%kairos.doctrine_behaviors.usageorderable.class%"
        arguments:
            - "@event_dispatcher"
            - "@security.context"
            - "@doctrine.orm.entity_manager"
            - "@kairos.doctrine_behaviors.reflection.class_analyzer"
            - "%kairos.doctrine_behaviors.reflection.is_recursive%"
            - "%kairos.doctrine_behaviors.usageorderable.usageorderable_trait%"
            - "%kairos.doctrine_behaviors.usageorderable.usagetimestamp_trait%"


    kairos.doctrine_behaviors.usageorderable_listener:
        class:   "%kairos.doctrine_behaviors.usageorderable_listener.class%"
        public:  false
        arguments:
            - "@kairos.doctrine_behaviors.reflection.class_analyzer"
            - "%kairos.doctrine_behaviors.reflection.is_recursive%"
            - "%kairos.doctrine_behaviors.usageorderable.usageorderable_trait%"
            - "%kairos.doctrine_behaviors.usageorderable.usagetimestamp_trait%"
        tags:
            - { name: doctrine.event_subscriber }